CREATE DOMAIN HUGEINT AS NUMERIC(1000, 0);


CREATE TYPE transfer_type AS enum(
	'TRANSFER_TYPE_UNSPECIFIED',
	'TRANSFER_TYPE_LOSS',
	'TRANSFER_TYPE_WIN',
	'TRANSFER_TYPE_CLOSE',
	'TRANSFER_TYPE_MTM_LOSS',
	'TRANSFER_TYPE_MTM_WIN',
	'TRANSFER_TYPE_MARGIN_LOW',
	'TRANSFER_TYPE_MARGIN_HIGH',
	'TRANSFER_TYPE_MARGIN_CONFISCATED',
	'TRANSFER_TYPE_MAKER_FEE_PAY',
	'TRANSFER_TYPE_MAKER_FEE_RECEIVE',
	'TRANSFER_TYPE_INFRASTRUCTURE_FEE_PAY',
	'TRANSFER_TYPE_INFRASTRUCTURE_FEE_DISTRIBUTE',
	'TRANSFER_TYPE_LIQUIDITY_FEE_PAY',
	'TRANSFER_TYPE_LIQUIDITY_FEE_DISTRIBUTE',
	'TRANSFER_TYPE_BOND_LOW',
	'TRANSFER_TYPE_BOND_HIGH',
	'TRANSFER_TYPE_WITHDRAW_LOCK',
	'TRANSFER_TYPE_WITHDRAW',
	'TRANSFER_TYPE_DEPOSIT',
	'TRANSFER_TYPE_BOND_SLASHING',
	'TRANSFER_TYPE_STAKE_REWARD',
	'TRANSFER_TYPE_TRANSFER_FUNDS_SEND',
	'TRANSFER_TYPE_TRANSFER_FUNDS_DISTRIBUTE',
	'TRANSFER_TYPE_CLEAR_ACCOUNT',
	'TRANSFER_TYPE_CHECKPOINT_BALANCE_RESTORE'
);

create table ledger
(
    ledger_entry_time       TIMESTAMP WITH TIME ZONE NOT NULL,
    account_from_id bytea                      NOT NULL,
    account_to_id   bytea                      NOT NULL,
    --quantity        HUGEINT                  NOT NULL,
    quantity NUMERIC(1000, 0) not null,
    tx_hash         BYTEA                    NOT NULL,
    vega_time       TIMESTAMP WITH TIME ZONE NOT NULL,
    transfer_time   TIMESTAMP WITH TIME ZONE NOT NULL,
    type            transfer_type
	--,
    -- PRIMARY KEY(ledger_entry_time)
);
